# -*- coding: utf-8 -*-
"""conditions_and_loops_discussion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugTg2yM0Sl2S3aJt7ud-EFYNzoszXP_5

# Comprehension Problems

### What is going on...
Let's do a quick review!
"""

### This is the syntax of a for-loop ###

#for variable in range(start, stop, step):
    # Code block to be executed

### This is the syntax of a while-loop ###

#while condition == true:
  # Code block to be executed


# Note: It is normal to forget the syntax! That is why google is your bff and you just need to google "for loop syntax" or "while loop syntax"
# and there are tons of resources. I usually just go to images to quickly check the syntax.

"""### Problem 1: Your turn!

Print i 10 times using both a for and while loop.
"""

# use a for loop here:

# use a while loop:

"""###Problem 2: Range()
Range is a cool function but there are a lot of parts to it so let's disect it!

What happens if the range is from (5, 5)?  How about from (10, 6)?  Try different step sizes: (10, 6, -1), (1, 10, 2). Write down all your observations and answer the following questions.

"""

# What does first number in range mean?
# What does the second argument in range mean? Is it included or excluded?
# What does the last argument do?

"""### Problem 3: Listness
How do you loop through elements in a list using a for loop?
"""

given_list = [10, 20, 30, 40, 50]

"""# Great work! Spend the rest of class doing application problems will be in your HW."""