# -*- coding: utf-8 -*-
"""Review_Command_Line_Solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hSapP-xD5XQ_vQdJ3uwZh2vq4p1gR2dk

# Command Line

The command line is an important tool that lets us manipulate files on our computer without having to use any other interfaces or our mouse. This is especially important if you need to remote ssh (basically logon) to another computer remotely. We do not expect you to have every command memorized, so when in doubt Google!

For each question, write out the command line commands (in your Terminal) you would use to complete the task. There may be multiple ways to do each task.

Note: You cannot run commands in Google Colab or Jupyter Notebook, but feel free to experiment in your own terminal or create a new markdown cell to describe what each command will do!

## Question 1

Create a directory called “python_decal_review” . Go into the decal directory. Then, create another directory inside of that called “final_project”.

**SOLUTION** \\
mkdir python_decal_review \\
cd python_decal_review \\
mkdir final_project

## Question 2

Count how many total files and directories are in your current directory. If there are more than 10 no need to count, you can just put 10.

**SOLUTION** \\
ls \\
List the files then manually count how many files

## Question 3

Someone asks you what path your “Review_Command_Line.ipnyb” is located at.

**SOLUTION** \\
pwd

## Question 4

Copy this file "Review_Command_Line.ipynb" into the "python_decal_review" directory you made earlier.

**SOLUTION** \\
cp Review_Command_Line.ipnyb python_decal_review

# Command Line in a Notebook

In this section of the review, you will become familiar with how to interact with your environment through the Jupyter Notebook. Pull up os documentation (https://docs.python.org/3/library/os.html) and peruse. From our first lecture on Command Line, try to identify some key words like files, paths, and directories. You will not need to understand it all right away.
"""

import os

"""## Question 5

The command `os.getcwd()` will output the current working directory, or where you are in your computer. Double-click on the markdown cell below, and write what the output is, and what it represents.
"""

os.getcwd()

"""This is a path! It will look different for everyone because everyone will have a different user profile name, and will keep their Downloads in a different place. This represents where the file that I am working in is located. If you do the previous exercises where you move the file into the "python_decal_review" directory that you made, it will describe wherever you made that directory."""

