# -*- coding: utf-8 -*-
"""Review_Command_Line.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjBGBkiHfYF6S53axiuNIadibN6Bq7a8

# Command Line

The command line is an important tool that lets us manipulate files on our computer without having to use any other interfaces or our mouse. This is especially important if you need to remote ssh (basically logon) to another computer remotely. We do not expect you to have every command memorized, so when in doubt Google!

For each question, write out the command line commands (in your Terminal) you would use to complete the task. There may be multiple ways to do each task.

Note: You cannot run commands in Google Colab or Jupyter Notebook, but feel free to experiment in your own terminal or create a new markdown cell to describe what each command will do!

## Question 1

Create a directory called “python_decal_review” . Go into the decal directory. Then, create another directory inside of that called “final_project”.

## Question 2

Count how many total files and directories are in your current directory. If there are more than 10 no need to count, you can just put 10.

## Question 3

Someone asks you what path your “Review_Command_Line.ipnyb” is located at.

## Question 4

Copy this file "Review_Command_Line.ipynb" into the "python_decal_review" directory you made earlier.

# Command Line in a Notebook

In this section of the review, you will become familiar with how to interact with your environment through the Jupyter Notebook. Pull up os documentation (https://docs.python.org/3/library/os.html) and peruse. From our first lecture on Command Line, try to identify some key words like files, paths, and directories. You will not need to understand it all right away.
"""

import os

"""## Question 5

The command `os.getcwd("file_name")` will output the current working directory, or where you are in your computer. Double-click on the markdown cell below, and write what the output is, and what it represents.
"""

##Your Code Here##

"""Your answer here."""

